version: "3.9"

services:
  trader:
    build: .
    environment:
      - POSTGRES_PASSWORD
    depends_on:
      - postgres
  
  postgres:
    image: postgres:16.0-bookworm
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=trader
      - POSTGRES_PASSWORD
      - POSTGRES_DB=trader

volumes:
  postgres-data: