version: "3.9"

services:
  trader:
    build: .
    environment:
      - POSTGRES_PASSWORD
    depends_on:
      - postgres
  
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - grafana-data:/var/lib/grafana
  
  postgres:
    image: postgres:16.0-bookworm
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=trader
      - POSTGRES_PASSWORD
      - POSTGRES_DB=trader

volumes:
  postgres-data: {}
  grafana-data: {}